# Generated by Django 4.2.20 on 2025-04-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_graduation_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='graduation_year',
        ),
    ]
