# Generated by Django 4.2.20 on 2025-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
