# Generated by Django 4.2.20 on 2025-04-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0003_alumniprofile_department_alumniprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
